from salary_calculator import calculate

test_cases = [
    # Test 0
    {
        "input_annual_gross": float(8000),
        "input_monthly_gross": float(8000 / 12),
        "input_tax_code": "1257L",
        "input_student_loan_plan": 1,
        "input_pension_type": "auto",
        "input_pension_percentage": 0.03,
        "output_tax": 0,
        "output_NIC": 0,
        "output_student_loan": 0,
        "output_pension": 4.40,
        "output_net_pay": 662.27,
    },
    # Test 1
    {
        "input_annual_gross": float(8000),
        "input_monthly_gross": float(8000 / 12),
        "input_tax_code": "1257L",
        "input_student_loan_plan": 4,
        "input_pension_type": "sac",
        "input_pension_percentage": 0.02,
        "output_tax": 0,
        "output_NIC": 0,
        "output_student_loan": 0,
        "output_pension": 13.33,
        "output_net_pay": 653.34,
    },
    # Test 2
    {
        "input_annual_gross": float(8000),
        "input_monthly_gross": float(8000 / 12),
        "input_tax_code": "1257L",
        "input_student_loan_plan": 0,
        "input_pension_type": "none",
        "input_pension_percentage": 0,
        "output_tax": 0,
        "output_NIC": 0,
        "output_student_loan": 0,
        "output_pension": 0,
        "output_net_pay": 666.67,
    },
    # Test 3
    {
        "input_annual_gross": float(8000),
        "input_monthly_gross": float(8000 / 12),
        "input_tax_code": "K253",
        "input_student_loan_plan": 6,
        "input_pension_type": "auto",
        "input_pension_percentage": 0.04,
        "output_tax": 174.33,
        "output_NIC": 0,
        "output_student_loan": 0,
        "output_pension": 5.87,
        "output_net_pay": 486.47,
    },
    # Test 4
    {
        "input_annual_gross": float(8000),
        "input_monthly_gross": float(8000 / 12),
        "input_tax_code": "K253",
        "input_student_loan_plan": 1,
        "input_pension_type": "sac",
        "input_pension_percentage": 0.06,
        "output_tax": 167.50,
        "output_NIC": 0,
        "output_student_loan": 0,
        "output_pension": 40,
        "output_net_pay": 459.17,
    },
    # Test 5
    {
        "input_annual_gross": float(8000),
        "input_monthly_gross": float(8000 / 12),
        "input_tax_code": "K253",
        "input_student_loan_plan": 0,
        "input_pension_type": "none",
        "input_pension_percentage": 0,
        "output_tax": 175.50,
        "output_NIC": 0,
        "output_student_loan": 0,
        "output_pension": 0,
        "output_net_pay": 491.17,
    },
    # Test 6
    {
        "input_annual_gross": float(35000),
        "input_monthly_gross": float(35000 / 12),
        "input_tax_code": "1050M",
        "input_student_loan_plan": 2,
        "input_pension_type": "auto",
        "input_pension_percentage": 0.03,
        "output_tax": 393.95,
        "output_NIC": 224.30,
        "output_student_loan": 57,
        "output_pension": 71.90,
        "output_net_pay": 2169.52,
    },
    # Test 7
    {
        "input_annual_gross": float(35000),
        "input_monthly_gross": float(35000 / 12),
        "input_tax_code": "1050M",
        "input_student_loan_plan": 1,
        "input_pension_type": "sac",
        "input_pension_percentage": 0.05,
        "output_tax": 379.17,
        "output_NIC": 206.80,
        "output_student_loan": 84,
        "output_pension": 145.83,
        "output_net_pay": 2100.87,
    },
    # Test 8
    {
        "input_annual_gross": float(35000),
        "input_monthly_gross": float(35000 / 12),
        "input_tax_code": "1050M",
        "input_student_loan_plan": 0,
        "input_pension_type": "none",
        "input_pension_percentage": 0,
        "output_tax": 408.33,
        "output_NIC": 224.30,
        "output_student_loan": 0,
        "output_pension": 0,
        "output_net_pay": 2284.04,
    },
    # Test 9
    {
        "input_annual_gross": float(35000),
        "input_monthly_gross": float(35000 / 12),
        "input_tax_code": "K680",
        "input_student_loan_plan": 4,
        "input_pension_type": "auto",
        "input_pension_percentage": 0.07,
        "output_tax": 697.89,
        "output_NIC": 224.30,
        "output_student_loan": 55,
        "output_pension": 167.77,
        "output_net_pay": 1771.71,
    },
    # Test 10
    {
        "input_annual_gross": float(35000),
        "input_monthly_gross": float(35000 / 12),
        "input_tax_code": "K680",
        "input_student_loan_plan": 2,
        "input_pension_type": "sac",
        "input_pension_percentage": 0.05,
        "output_tax": 706.66,
        "output_NIC": 206.80,
        "output_student_loan": 44,
        "output_pension": 145.83,
        "output_net_pay": 1813.38,
    },
    # Test 11
    {
        "input_annual_gross": float(35000),
        "input_monthly_gross": float(35000 / 12),
        "input_tax_code": "K680",
        "input_student_loan_plan": 0,
        "input_pension_type": "none",
        "input_pension_percentage": 0,
        "output_tax": 765,
        "output_NIC": 224.30,
        "output_student_loan": 0,
        "output_pension": 0,
        "output_net_pay": 1927.37,
    },
    # Test 12
    {
        "input_annual_gross": float(85000),
        "input_monthly_gross": float(85000 / 12),
        "input_tax_code": "1100T",
        "input_student_loan_plan": 6,
        "input_pension_type": "auto",
        "input_pension_percentage": 0.10,
        "output_tax": 1691.56,
        "output_NIC": 434.88,
        "output_student_loan": 320,
        "output_pension": 366.92,
        "output_net_pay": 4269.97,
    },
    # Test 13
    {
        "input_annual_gross": float(85000),
        "input_monthly_gross": float(85000 / 12),
        "input_tax_code": "1100T",
        "input_student_loan_plan": 2,
        "input_pension_type": "sac",
        "input_pension_percentage": 0.12,
        "output_tax": 1498.33,
        "output_NIC": 417.88,
        "output_student_loan": 356,
        "output_pension": 850,
        "output_net_pay": 3961.12,
    },
    # Test 14
    {
        "input_annual_gross": float(85000),
        "input_monthly_gross": float(85000 / 12),
        "input_tax_code": "1100T",
        "input_student_loan_plan": 0,
        "input_pension_type": "none",
        "input_pension_percentage": 0,
        "output_tax": 1838.33,
        "output_NIC": 434.88,
        "output_student_loan": 0,
        "output_pension": 0,
        "output_net_pay": 4810.12,
    },
    # Test 15
    {
        "input_annual_gross": float(85000),
        "input_monthly_gross": float(85000 / 12),
        "input_tax_code": "K750",
        "input_student_loan_plan": 1,
        "input_pension_type": "auto",
        "input_pension_percentage": 0.09,
        "output_tax": 2322.91,
        "output_NIC": 434.88,
        "output_student_loan": 472,
        "output_pension": 330.23,
        "output_net_pay": 3523.31,
    },
    # Test 16
    {
        "input_annual_gross": float(85000),
        "input_monthly_gross": float(85000 / 12),
        "input_tax_code": "K750",
        "input_student_loan_plan": 6,
        "input_pension_type": "sac",
        "input_pension_percentage": 0.13,
        "output_tax": 2086.66,
        "output_NIC": 416.47,
        "output_student_loan": 264,
        "output_pension": 920.83,
        "output_net_pay": 3395.37,
    },
    # Test 17
    {
        "input_annual_gross": float(85000),
        "input_monthly_gross": float(85000 / 12),
        "input_tax_code": "K750",
        "input_student_loan_plan": 0,
        "input_pension_type": "none",
        "input_pension_percentage": 0,
        "output_tax": 2455,
        "output_NIC": 434.88,
        "output_student_loan": 0,
        "output_pension": 0,
        "output_net_pay": 4193.45,
    },
    # Test 18
    {
        "input_annual_gross": float(140000),
        "input_monthly_gross": float(140000 / 12),
        "input_tax_code": "1257L",
        "input_student_loan_plan": 6,
        "input_pension_type": "auto",
        "input_pension_percentage": 0.03,
        "output_tax": 3579.34,
        "output_NIC": 526.55,
        "output_student_loan": 595,
        "output_pension": 110.08,
        "output_net_pay": 6855.70,
    },
    # Test 19
    {
        "input_annual_gross": float(140000),
        "input_monthly_gross": float(140000 / 12),
        "input_tax_code": "1257L",
        "input_student_loan_plan": 1,
        "input_pension_type": "sac",
        "input_pension_percentage": 0.08,
        "output_tax": 3246,
        "output_NIC": 507.88,
        "output_student_loan": 800,
        "output_pension": 933.33,
        "output_net_pay": 6179.46,
    },
    # Test 20
    {
        "input_annual_gross": float(140000),
        "input_monthly_gross": float(140000 / 12),
        "input_tax_code": "1257L",
        "input_student_loan_plan": 0,
        "input_pension_type": "none",
        "input_pension_percentage": 0,
        "output_tax": 3628.88,
        "output_NIC": 526.55,
        "output_student_loan": 0,
        "output_pension": 0,
        "output_net_pay": 7511.24,
    },
    # Test 21
    {
        "input_annual_gross": float(140000),
        "input_monthly_gross": float(140000 / 12),
        "input_tax_code": "K200",
        "input_student_loan_plan": 6,
        "input_pension_type": "auto",
        "input_pension_percentage": 0.03,
        "output_tax": 4125.72,
        "output_NIC": 526.55,
        "output_student_loan": 595,
        "output_pension": 110.08,
        "output_net_pay": 6309.32,
    },
    # Test 22
    {
        "input_annual_gross": float(140000),
        "input_monthly_gross": float(140000 / 12),
        "input_tax_code": "K200",
        "input_student_loan_plan": 1,
        "input_pension_type": "sac",
        "input_pension_percentage": 0.08,
        "output_tax": 3755.25,
        "output_NIC": 507.88,
        "output_student_loan": 800,
        "output_pension": 933.33,
        "output_net_pay": 5670.21,
    },
    # Test 23
    {
        "input_annual_gross": float(140000),
        "input_monthly_gross": float(140000 / 12),
        "input_tax_code": "K200",
        "input_student_loan_plan": 0,
        "input_pension_type": "none",
        "input_pension_percentage": 0,
        "output_tax": 4175.25,
        "output_NIC": 526.55,
        "output_student_loan": 0,
        "output_pension": 0,
        "output_net_pay": 6964.87,
    },
    # Test 24
    {
        "input_annual_gross": float(23000),
        "input_monthly_gross": float(23000 / 12),
        "input_tax_code": "1257L",
        "input_student_loan_plan": 1,
        "input_pension_type": "none",
        "input_pension_percentage": 0,
        "output_tax": 173.83,
        "output_NIC": 104.30,
        "output_student_loan": 7,
        "output_pension": 0,
        "output_net_pay": 1631.54,
    },
    # Test 25
    {
        "input_annual_gross": float(22014),
        "input_monthly_gross": float(22014 / 12),
        "input_tax_code": "1257L",
        "input_student_loan_plan": 1,
        "input_pension_type": "none",
        "input_pension_percentage": 0,
        "output_tax": 157.40,
        "output_NIC": 94.44,
        "output_student_loan": 0,
        "output_pension": 0,
        "output_net_pay": 1582.66,
    },
    # Test 26
    {
        "input_annual_gross": float(28000),
        "input_monthly_gross": float(28000 / 12),
        "input_tax_code": "1257L",
        "input_student_loan_plan": 2,
        "input_pension_type": "none",
        "input_pension_percentage": 0,
        "output_tax": 257.17,
        "output_NIC": 154.30,
        "output_student_loan": 5,
        "output_pension": 0,
        "output_net_pay": 1916.86,
    },
    # Test 27
    {
        "input_annual_gross": float(27294),
        "input_monthly_gross": float(27294 / 12),
        "input_tax_code": "1257L",
        "input_student_loan_plan": 2,
        "input_pension_type": "none",
        "input_pension_percentage": 0,
        "output_tax": 245.40,
        "output_NIC": 147.24,
        "output_student_loan": 0,
        "output_pension": 0,
        "output_net_pay": 1881.86,
    },
    # Test 28
    {
        "input_annual_gross": float(28000),
        "input_monthly_gross": float(28000 / 12),
        "input_tax_code": "1257L",
        "input_student_loan_plan": 4,
        "input_pension_type": "none",
        "input_pension_percentage": 0,
        "output_tax": 257.17,
        "output_NIC": 154.30,
        "output_student_loan": 0,
        "output_pension": 0,
        "output_net_pay": 1919.86,
    },
    # Test 29
    {
        "input_annual_gross": float(27659),
        "input_monthly_gross": float(27659 / 12),
        "input_tax_code": "1257L",
        "input_student_loan_plan": 4,
        "input_pension_type": "none",
        "input_pension_percentage": 0,
        "output_tax": 251.48,
        "output_NIC": 150.89,
        "output_student_loan": 0,
        "output_pension": 0,
        "output_net_pay": 1902.55,
    },
    # Test 30
    {
        "input_annual_gross": float(27000),
        "input_monthly_gross": float(27000 / 12),
        "input_tax_code": "1257L",
        "input_student_loan_plan": 5,
        "input_pension_type": "none",
        "input_pension_percentage": 0,
        "output_tax": 240.50,
        "output_NIC": 144.30,
        "output_student_loan": 15,
        "output_pension": 0,
        "output_net_pay": 1850.20,
    },
    # Test 31
    {
        "input_annual_gross": float(24999),
        "input_monthly_gross": float(24999 / 12),
        "input_tax_code": "1257L",
        "input_student_loan_plan": 5,
        "input_pension_type": "none",
        "input_pension_percentage": 0,
        "output_tax": 207.15,
        "output_NIC": 124.29,
        "output_student_loan": 0,
        "output_pension": 0,
        "output_net_pay": 1751.81,
    },
    # Test 32
    {
        "input_annual_gross": float(22000),
        "input_monthly_gross": float(22000 / 12),
        "input_tax_code": "1257L",
        "input_student_loan_plan": 6,
        "input_pension_type": "none",
        "input_pension_percentage": 0,
        "output_tax": 157.17,
        "output_NIC": 94.30,
        "output_student_loan": 0,
        "output_pension": 0,
        "output_net_pay": 1576.86,
    },
    # Test 33
    {
        "input_annual_gross": float(20999),
        "input_monthly_gross": float(20999 / 12),
        "input_tax_code": "1257L",
        "input_student_loan_plan": 6,
        "input_pension_type": "none",
        "input_pension_percentage": 0,
        "output_tax": 140.48,
        "output_NIC": 84.29,
        "output_student_loan": 0,
        "output_pension": 0,
        "output_net_pay": 1525.15,
    },
    # Test 34
    {
        "input_annual_gross": float(85000),
        "input_monthly_gross": float(85000 / 12),
        "input_tax_code": "BR",
        "input_student_loan_plan": 0,
        "input_pension_type": "none",
        "input_pension_percentage": 0,
        "output_tax": 1416.67,
        "output_NIC": 434.88,
        "output_student_loan": 0,
        "output_pension": 0,
        "output_net_pay": 5231.78,
    },
    # Test 35
    {
        "input_annual_gross": float(25000),
        "input_monthly_gross": float(25000 / 12),
        "input_tax_code": "D0",
        "input_student_loan_plan": 0,
        "input_pension_type": "none",
        "input_pension_percentage": 0,
        "output_tax": 833.33,
        "output_NIC": 124.30,
        "output_student_loan": 0,
        "output_pension": 0,
        "output_net_pay": 1125.70,
    },
    # Test 36
    {
        "input_annual_gross": float(85000),
        "input_monthly_gross": float(85000 / 12),
        "input_tax_code": "D1",
        "input_student_loan_plan": 0,
        "input_pension_type": "none",
        "input_pension_percentage": 0,
        "output_tax": 3187.50,
        "output_NIC": 434.88,
        "output_student_loan": 0,
        "output_pension": 0,
        "output_net_pay": 3460.95,
    },
    # Test 37
    {
        "input_annual_gross": float(25000),
        "input_monthly_gross": float(25000 / 12),
        "input_tax_code": "0T",
        "input_student_loan_plan": 0,
        "input_pension_type": "none",
        "input_pension_percentage": 0,
        "output_tax": 416.67,
        "output_NIC": 124.30,
        "output_student_loan": 0,
        "output_pension": 0,
        "output_net_pay": 1542.36,
    },
]


for idx, test_case in enumerate(test_cases):
    (
        monthly_gross,
        tax,
        national_insurance,
        student_loan,
        monthly_pension,
        net_pay,
    ) = calculate(
        test_case["input_annual_gross"],
        test_case["input_monthly_gross"],
        test_case["input_tax_code"],
        test_case["input_student_loan_plan"],
        test_case["input_pension_percentage"],
        test_case["input_pension_type"],
    )

    difference = round(net_pay - test_case["output_net_pay"], 2)

    if difference >= -0.05 and difference <= 0.05:
        print(f"\033[32mTest {idx} PASSED\033[0m")
    elif difference <= -0.06 and difference >= 0.06:
        print(
            f"\033[31mTEST {idx} FAILED: DIFFERENCE OF {difference} - Received: {net_pay} | Expected: {test_case['output_net_pay']}\033[0m"
        )
    else:
        print(
            f"\033[33mTEST {idx} PASSED WITH WARNINGS: ROUNDING DIFFERENCE OF {difference} - Net Pay Received: {net_pay} | Net Pay Expected: {test_case['output_net_pay']}\033[0m"
        )
